export const API_URL = process.env.NEXT_PUBLIC_API_URL
export const MAXIMUN_IN_PRIORITY_TASKS = Number(
  process.env.NEXT_PUBLIC_MAXIMUN_IN_PRIORITY_TASKS
)
export const MAXIMUM_BACKLOG_QUANTITY = Number(
  process.env.NEXT_PUBLIC_MAXIMUM_BACKLOG_QUANTITY
)
