export const API_URL = process.env.NEXT_PUBLIC_API_URL
export const MAX_IN_PROGRESS_TASKS =
  process.env.NEXT_PUBLIC_MAX_IN_PROGRESS_TASKS
export const MAXIMUM_BACKLOG_QUANTITY =
  process.env.NEXT_PUBLIC_MAXIMUM_BACKLOG_QUANTITY
